name: 'Tank you Action'
description: 'Say "Thank you" to new pull resquest'
author: "Vinicius"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true

  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

    runs:
      using: 'node14'
      main:  'dist/index.js'